---
- name: "K3s | Dowload k3s installation script"
  ansible.builtin.get_url:
    url: "https://get.k3s.io/"
    dest: "/usr/local/bin/{{ k3s_install_script }}"
    mode: '0755'
    owner: root
    group: root
    timeout: 120

- name: "K3s | Install k3s server"
  ansible.builtin.command:
    cmd: "/usr/local/bin/{{ k3s_install_script }}"
  environment:
    INSTALL_K3S_SKIP_START: "true"
    INSTALL_K3S_EXEC: "server {{ k3s_server_install_args }}"
    K3S_TOKEN: "{{ k3s_token }}"
    INSTALL_K3S_VERSION: "{{ k3s_version }}"
  args:
    creates: "{{ k3s_install_lockfile }}"
  register: k3s_install
  changed_when: true

- name: "K3s | Enable k3s server service"
  ansible.builtin.systemd:
    name: k3s
    state: started
    enabled: true
    daemon_reload: true

- name: "K3s | Restart k3s for certificates renewal - Server"
  ansible.builtin.cron:
    name: "Restart k3s for certificates renewal every 2 months"
    job: "/usr/bin/timeout --preserve-status -s 9 10m /bin/systemctl restart k3s.service"
    user: root
    hour: "5"
    minute: "{{ k3s_cronjob_random_minutes_list | random }}"
    day: "1"
    month: "*/2"
    state: present
  when: (k3s_install_cert_cronjob | bool)
